"""empty message

Revision ID: 015e5315bd4f
Revises: dcc39f3243bc
Create Date: 2026-01-07 18:59:25.019100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '015e5315bd4f'
down_revision: Union[str, Sequence[str], None] = 'dcc39f3243bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalbests', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalbests', 'order')
    # ### end Alembic commands ###
