"""empty message

Revision ID: 52f7ec01c8ae
Revises: 6ae48025abc4
Create Date: 2026-02-24 12:05:01.743107

"""
from typing import Sequence, Union
from app.api.runs.models import PersonalBests, PersonalBestType
from app.core.database_manager import database_manager


# revision identifiers, used by Alembic.
revision: str = '52f7ec01c8ae'
down_revision: Union[str, Sequence[str], None] = '6ae48025abc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    database_manager.startup()

    with database_manager.get_session_context() as session:
        session.add(PersonalBests(
            title='Fastest 5km',
            max_distance_m=5005,
            min_distance_m=5000,
            sort_order=1,
            user_id=4,
            type=PersonalBestType.SPEED
        ))
        session.commit()

        session.add(PersonalBests(
            title='Longest Run',
            sort_order=2,
            user_id=4,
            type=PersonalBestType.DISTANCE
        ))
        session.commit()

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
