"""empty message

Revision ID: 6ae48025abc4
Revises: 873077fa01cf
Create Date: 2026-01-07 20:05:19.772557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ae48025abc4'
down_revision: Union[str, Sequence[str], None] = '873077fa01cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalbests', sa.Column('min_distance_m', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalbests', 'min_distance_m')
    # ### end Alembic commands ###
