"""empty message

Revision ID: 873077fa01cf
Revises: 015e5315bd4f
Create Date: 2026-01-07 19:00:31.012705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '873077fa01cf'
down_revision: Union[str, Sequence[str], None] = '015e5315bd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalbests', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.drop_column('personalbests', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalbests', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('personalbests', 'sort_order')
    # ### end Alembic commands ###
