"""empty message

Revision ID: 8c03a116491d
Revises: 545a4e02bb0c
Create Date: 2025-09-29 15:05:26.535960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c03a116491d'
down_revision: Union[str, Sequence[str], None] = '545a4e02bb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('run_date', sa.Date(), nullable=False))
    op.drop_column('run', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('run', 'run_date')
    # ### end Alembic commands ###
