"""empty message

Revision ID: dcc39f3243bc
Revises: 8c03a116491d
Create Date: 2026-01-07 18:48:17.357732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcc39f3243bc'
down_revision: Union[str, Sequence[str], None] = '8c03a116491d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalbests',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('DISTANCE', 'DURATION', 'SPEED', name='personalbesttype'), nullable=False),
    sa.Column('max_distance_m', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalbests_id'), 'personalbests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personalbests_id'), table_name='personalbests')
    op.drop_table('personalbests')
    # ### end Alembic commands ###
